Ot293 16/model migration controller organization
alkemyTech/OT293-server pull request #7
Opened 2022-09-15 03:39 UTC by lucasambrosini1

Summary:

- Organization model.
- Organization migration.
- Organization base controller.

2022-09-16 05:52 UTC, kevinderitis requested changes

2022-09-16 05:52 UTC, kevinderitis commented on controllers/organizationController.js
> +
Completar metodos.

2022-09-16 05:52 UTC, kevinderitis commented on migrations/create-organization.js
> +  up: async (queryInterface, Sequelize) => {
El nombre de la migration me resulta extraño, testeaste si te la tomaba de esa manera? Debes generarla desde los comandos de sequelize.

2022-09-16 19:37 UTC, lucasambrosini1 commented on migrations/create-organization.js
> +  up: async (queryInterface, Sequelize) => {
Corregido.

2022-09-19 13:53 UTC, kevinderitis approved these changes

2022-09-19 13:53 UTC, merged