swagger is working - OT293-90
alkemyTech/OT293-server pull request #75
Opened 2022-10-07 22:37 UTC by angelaguirrejs

2022-10-10 19:12 UTC, kevinderitis requested changes

2022-10-10 19:12 UTC, kevinderitis commented on app.js
> -<<<<<<< HEAD
Habria que solucionar esto.

2022-10-10 23:19 UTC, angelaguirrejs commented on app.js
> -<<<<<<< HEAD
Ya está resulto

2022-10-12 13:36 UTC, kevinderitis approved these changes

2022-10-12 13:36 UTC, merged